name: Deploy

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install /functions dependencies
        working-directory: ./functions
        run: npm ci

      - name: Install firebase dependencies
        working-directory: ./functions
        run: npm i -D firebase-tools

      - name: Deploy
        run: npx firebase deploy --token ${{ secrets.FIREBASE_CI_TOKEN }}
